name: cositapp
description: App de gestión de pedidos de pastelería - Cositas de la Abuela
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.0
  intl: 0.20.2
  table_calendar: ^3.0.9
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  permission_handler: ^11.2.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  file_picker: ^8.0.0+1
  archive: ^3.4.10
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/data/resources/cositasdelaabuela.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "lib/data/resources/cositasdelaabuela.png"
  min_sdk_android: 24
  adaptive_icon_background: "#F8BBD9"
  adaptive_icon_foreground: "lib/data/resources/cositasdelaabuela.png"
